### ISSUE TITLE
clean-ns removes fully qualified namespaces

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#107]
```clj
(ns example
  (:require [ring.middleware.cookies]))

(def my-routes)

(def app
  (ring.middleware.cookies/wrap-cookies my-routes))
```

Running `(cljr-clean-ns)` on this will remove the require.

**Comment by expez** [comment]
I can't reproduce this by writing `nrepl-refactor` test cases.  I did found a bug in the pprinting, though.  I'd like all non-libspec vectors to come first:

```
(:require
  [clojure data edn
   [instant :as inst]
   [pprint :refer [cl-format formatter get-pretty-writer]]
   [string :refer :all :rename {replace foo, reverse bar}]
   [test :refer :all]
   xml]
  clojure.test.junit
```

Notice how `xml` is last. I think this hurts readability quite a bit.

Does this occur in one of your projects, so I can clone that to reproduce?

**Comment by magnars** [comment]
Here you go: https://github.com/magnars/bug-examples/tree/cljr-fully-qualified-namespace-cleanup

**Comment by expez** [comment]
Thanks, the grammar didn't support the optional `[ ]` around the libspec.  When trying to reproduce this my mind just disregarded the enclosing brackets entirely: I thought the problem was with the use of fully qualified symbols :)

This is fixed [here](https://github.com/clojure-emacs/refactor-nrepl/commit/c42cd8000048a78de07a42b2e761d9e9e73703c7)

**Comment by magnars** [comment]
Aha, nice. :) Thanks!

**Comment by magnars** [comment]
Something new went wrong now. This:

```clj
(ns no-adventur.engine.play
  (:require [clj-time.core :as time]
            [clojure.set :as set]
            [no-adventur.content.badges :refer [find-new-badges]]
            [no-adventur.engine.changes :as c]
            [no-adventur.engine.execute-room :as x]
            [no-adventur.engine.flashes :as flashes]
            [no-adventur.engine.prepare-view :as v]
            [no-adventur.storage.protocol :refer :all]))
```

turns into this:

```clj
(ns no-adventur.engine.play
(:require [clj-time.core :as time]
[clojure.set :as set]
[no-adventur.content.badges :refer [find-new-badges]]
[no-adventur.engine
[[changes :as c]
 [execute-room :as x]
 [flashes :as flashes]
 [prepare-view :as v]]
[no-adventur.storage.protocol :refer :all]))
```

With an unbalanced parenthesis warning.

**Comment by expez** [comment]
mm, noticed that as well.  The test for the pprint code is in a `comment` because the ordering of elements in hashmaps changed i version 1.6.  I just ran `clean-ns` tests to verify the fix and not the entire gammut. 

 I've pushed yet another version to clojars :p  This time I've also crossed my fingers so everything should be hunky-dory!

**Comment by expez** [comment]
I really regret the decision to take on pprinting, that shit is surprisingly hard, with tons of edge-cases in nested conditionals, and annoying to test.

**Comment by benedekfazekas** [comment]
did not u say u will let the client take care of that?

**Comment by expez** [comment]
Just the actual indentation.  `refactor-nrepl` has to insert spaces and newlines in the right places.
