### ISSUE TITLE
Option to use full libspecs instead of prefix for clean-ns

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#108]
The prefix form is rarely used, and I don't want clj-refactor to be so opinionated on this topic that people end up avoiding clean-ns.

I can understand if you're tired of this function now, @expez, so if you give me a little bit of direction, I can try to piece together a PR for this option.

Thoughts?

**Comment by expez** [comment]
I think the prefix form is less used because it's a bit more trouble, but I also think it's superior.  In other words I don't want to just remove this functionality.  If you want to add an option, though, that's fine.

The point of extension would be here:

```(defn- pprint-prefix-form [[name & libspecs]]```.  The input here is e.g. `(clojure data edn xml [string :as str] [set :refer [union])`.  All you'd have to do is to write an equivalent which takes the first element, the prefix `clojure` and prepends it everywhere.  

Another point of contention is if `clojure.xml` is an OK libspec, or if `[clojure.xml]` should be used.  I favor the brevity of the former, but you favored the latter in one of the bug reports and I can see arguments for that position as well.  So you might want to add another extension point which wraps all symbols in vectors as well.

The reason I went with the opinionated route is that we can add customization points endlessly, but to what end? The `ns` really doesn't matter, as long as the code compiles.  All this is just to make it slightly easier to work with the few times you have to visit it manually.  `intellij` has dependency management down to a T and just puts the entire import section behind a fold that is hidden by default, because it's all just noise and nothing anyone should spend time on.

**Comment by benedekfazekas** [comment]
i am more leaning towards @magnars point here. really good u r opinionated expez: easier to relate to ur arguments.

basically i think ns declaration has important info in it which i want to read easily so i favour readability over brevity here. i think one of the pitfalls with cider/refactor is to make it too IDE like. hiding/folding the ns decl would be too IDE for me (i know u r not proposing folding it).

**Comment by expez** [comment]
Brevity and helpful indentations aids readability so much imo. Compare these two:

```clj
(:require [clojure.tools.namespace.parse :refer [read-ns-decl]]
            [clojure.tools.nrepl
             [middleware :refer [set-descriptor!]]
             [misc :refer [response-for]]
             [transport :as transport]]
            [refactor-nrepl.ns
             [constructor :refer [rebuild-ns-form]]
             [dependencies :refer [extract-dependencies]]
             [helpers :refer [get-ns-component]]
             [pprint :refer [pprint-ns]]])
```
```clj
(:require [clojure.tools.namespace.parse :refer [read-ns-decl]]
            [clojure.tools.nrepl.middleware :refer [set-descriptor!]]
            [clojure.tools.nrepl.misc :refer [response-for]]
            [clojure.tools.nrepl.transport :as transport]
            [refactor-nrepl.ns.constructor :refer [rebuild-ns-form]]
            [refactor-nrepl.ns.dependencies :refer [extract-dependencies]]
            [refactor-nrepl.ns.helpers :refer [get-ns-component]]
            [refactor-nrepl.ns.pprint :refer [pprint-ns]])
```

Due to the way the former is indented I can immediately see that multiple namespaces are pulled in from `clojure.tools.nrepl.middleware`.  Look at the latter ns form and try to answer the question "how many libs are pulled in from clojure.tools.nrepl.middleware?".  I found it **a lot** slower to count occurrences in the non-prefixed form because I have to scan both vertically and horizontally.

Those are my practical concerns, on top of that the latter ns form contains so much replication that my brain instantly screams "someone should write a macro for that!"

**Comment by benedekfazekas** [comment]
just on a different note: if you use `clojure.tools.analyzer` in the same ns that would be turned into something like:
```clojure
[clojure.tools
   [nrepl.middleware :refer [set-descriptor!]]
   [analyzer.ast :refer [nodes]]]
```
is not that more misleading than helping...

is not this all kinda hinting that prefix or no prefix is a lot a question of personal taste? if so this is really a point we should make configurable...

**Comment by expez** [comment]
The libspec you just posted is invalid.  Libspecs that are part of a prefix vector cannot themselves contain a prefix.

**Comment by magnars** [comment]
A couple points:

- The Java imports handling in IntelliJ and Eclipse is highly configurable, and in my experience most large development teams have a policy about exactly how the imports should look.

- Emacs and CIDER isn't as ubiquitous as those two editors are for Java - and clj-refactor isn't much used amongst Emacs users either. Being opinionated contrary to the normal style when we're looking for adoption makes us less likely to succeed - even if you could argue that our style is objectively better.

So, I think it's great to offer both styles.

**Comment by benedekfazekas** [comment]
expez: haha, you are of course right. sry about it.
