### ISSUE TITLE
cljr-remove-unused-requires considers text in docstrings as references

### ISSUE THREAD

**Issue by mtnygard** [clojure-emacs/clj-refactor.el#176]
E.g., a requires like [foo.types :as t] will be kept if a docstring has "t/Any" in it.

**Comment by expez** [comment]
`clean-ns` is meant to replace all the other functions doing various cleanup on the ns.  It was written because the old stuff is regexp based and will get tripped up on docstrings and whatnot.

I consider the other functions to be deprecated so I don't want to work on them, but I don't want to remove them either because they work for clojurescript which `clean-ns` does not.  

If you want to fix this I'm cool with merging a patch which skips past any matches in docstrings and comments.

**Comment by mtnygard** [comment]
I wish I could fix it, but my elisp is not strong.

**Comment by benedekfazekas** [comment]
have u given a try to `cleans-ns` tho?
