### ISSUE TITLE
Discover Mode

### ISSUE THREAD

**Issue by jakepearson** [clojure-emacs/clj-refactor.el#177]
I've been trying `clj-refactor` off and on for quite a while. I've found it challenging to figure out which refactorings are available so I created a context menu for refactorings based on [discover.el](https://github.com/mickeynp/discover.el). You can see the source of it [here](https://github.com/RallySoftware/rally-emacs/blob/master/rally/refactor.el). It is activated by pressing `M-RET` which is nice as it the same keystroke we use in IntelliJ.

Do you have any interest in including something like this in `clj-refactor`? If so, I can try to put together a pull request.

**Comment by expez** [comment]
Cool!  You should definitely considering publishing this as a separate package, but I don't want to add a dependence on discover.el to core.  We've had this discussion a few times, most recently with regard to [cljr-helm](https://github.com/philjackson/cljr-helm).

If you do decide to publish, the variable `cljr--all-helpers` was created to make cljr-helm easier to write and maintain.  Even though it's marked as package private we consider it part of the public api since it's used by at least one external package now.
