### ISSUE TITLE
clean-ns and 1.7 reader conditionals.

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/clj-refactor.el#183]
clj-refactor currently treats [reader conditionals](http://clojure.org/reader#The%20Reader--Reader%20Conditionals) as malformed. An example:

```clj
(ns example
  (:require [#?(:cljs example.ui.foo :clj example.foo) :as foo]
            [#?(:cljs example.ui.bar :clj example.bar) :as bar]))
```

I realise this is a non-trivial problem. My suggestion is that clean-ns just leaves them as-is.

**Comment by expez** [comment]
How should this look? There are a lot of possibilities in terms of where we should put the reader conditionals.  We could guard each libspec, or we could produce two versions of the content of the `:require` and `:import` sections.

I think I would prefer 

```clj
(ns example
  (:require #?@(:cljs ...)
            #?@(:clj ...)))
```

because it would look less noisy and require less thinking when reading, but there would probably be more replication in this variant.  This version would also be much easier to produce.

**Comment by magnars** [comment]
I guess people will have all sorts of different reader conditional setups. We could try to mandate the form you prefer, and just refuse to run clean-ns if we spot any other versions.

**Comment by expez** [comment]
https://github.com/clojure-emacs/refactor-nrepl/commit/cb18612c583037de9cd40e0b343e5af71b8ae47d
