### ISSUE TITLE
Behavior of `cljr-rename-symbol` can be frustrating

### ISSUE THREAD

**Issue by ccann** [clojure-emacs/clj-refactor.el#203]
It's often frustrating to invoke `cljr-rename-symbol`, type my new variable name, and then see that an unrelated error in the namespace has prevented the renaming. Personally I would prefer if errors in the namespace were called out before prompting the user for the replacement text, what do you think?

I don't know how the internals work, so this suggestion could be moot. I do like the behavior of a similar function in the python environment Elpy. The behavior of `C-c C-e` in [elpy](https://github.com/jorgenschaefer/elpy) is to rename the symbol regardless of errors. Often I just want to rename the symbol even though things are broken.

Apologies if this is a dupe and thanks for the awesome package!!

**Comment by expez** [comment]
We've had this discussion on the team a few times, but with regard to `find-usages`, and have recently added the ability to do `find-usages` in a best-effort manner.

The reason it works this way, for now, is that we query the middleware for all the occurrences of the symbol.  To do that the middleware builds an AST using `tools.analyzer`.  If the namespace is unparseable the constructino of said AST will fail and we abort.

We can certainly change the function to first query the middleware for occurrences, though, and this seems like a good idea to me.  The only reason it's done the way it is now is because it's idiomatic, in emacs, to prompt the user for input the the interactive function in the beginning.

Why do you think a partial renaming is a good idea?  I have a hard time imagining anything more frustrating than having say 31 of 52 occurrences of a symbol across a project renamed, leaving 21 occurrences pointing to some non-existing symbol which you then have to track down manually.  At that point, it seems to me, we've done more harm than good.

**Comment by ccann** [comment]
I didn't mean to suggest that partial renaming is a good idea, I agree with you. I was just trying to express that elpy's refactor is seemingly independent of the error-state (bad code, I mean) of the buffer.

Yeah I think for me this would be a case where the idiomatic approach just gets in the way a bit, unfortunately.

Thanks for the response!
