### ISSUE TITLE
Inconsistent versions

### ISSUE THREAD

**Issue by bilus** [clojure-emacs/clj-refactor.el#227]
The current clj-refactor version in elpa is 1.2.0-snapshot while the Readme suggests to put [refactor-nrepl "1.1.0"] into profiles.clj. This configuration produces a warning in nREPL in Emacs.

**Comment by expez** [comment]
Yes, the readme is somewhat conservative in that it doesn't recommend running the bleeding edge and instead recommends using the latest stable release.  If you'd picked melpa-stable, instead of melpa, as your package archive of choice you wouldn't have seen this warning.

I take pride in fixing issues quickly, but you should be aware that some breakage is to be expect when you're tracking the `master` branch.

**Comment by bilus** [comment]
Sounds reasonable. Thanks.
