### ISSUE TITLE
extract-def could do some basic checks for used vars

### ISSUE THREAD

**Issue by Malabarba** [clojure-emacs/clj-refactor.el#228]
Take the following example. If I use `extrac-def` on `{:id (random-str)}`, the def will be created at the top of the file, even though it depends on `random-str`.

    (defn random-str []
      (->> #(format "%x" (rand-int 15))
           (repeatedly 10)
           (apply str)))
    
    (defn test []
      {:id (random-str)})

It's not a huge deal, but perhaps this command could do something like `(split-string string-being-moved "[^-!/?_[:word:]]" t)` to get a list of the used symbols, and then make sure to put the `def` after any definitions of these symbols.

**Comment by expez** [comment]
I think this is both a great and a terrible idea at the same time :p 

* I'd love for this op to be a bit more intelligent, so you don't have to refactor your refactored code so it compiles.
* I think it's a code smell to have defs, for dynamics vars or constants, anywhere but the top of the file because that's where people expect them to be.

I'd probably find some way to rewrite this, perhaps even leaving stuff inline, to avoid having defs anywhere else in the file.  Then again, who am I to decide how **you** should structure your code? :p

**Comment by Malabarba** [comment]
> I think it's a code smell to have defs, for dynamics vars or constants, anywhere but the top of the file because that's where people expect them to be.

True. But although I used a `defn` in my example, the same would happen if the extracted code depends on a variable or constant. :)

**Comment by expez** [comment]
I'm thinking it would be good enough if any new def is appended to the end of the group of defs occurring at the beginning of the ns.  That way variables and constants can be created referencing other existing variables or constant as well as functions in other namespaces.

Does that sound good to you @Malabarba?

**Comment by Malabarba** [comment]
> Does that sound good to you @Malabarba?

Yep. :+1:
