### ISSUE TITLE
Cheatsheet

### ISSUE THREAD

**Issue by bilus** [clojure-emacs/clj-refactor.el#230]
Thank you for a wonderful package! It's nearly perfect (cljs aside).

I put a link to a cheatsheet in the wiki (under the list of refactorings). Please feel free to edit/remove it as you see fit. I'm also looking to any comments you may have.

Thanks again.

**Comment by expez** [comment]
That's awesome!  Thanks @bilus! 

cljs (and cljc) support is definitely the focus going forward.  So far I've ported the following middleware functions:

* clean-ns 
* rename-file-or-dir
* add-missing-libspec 

When improving `cljr-slash` I also took `cljs` into account.  The version searches your projects for aliases that you've used before so if you type `zip/` and you've only used rewrite-clj's `zip` namespace then that will get required instead of say `clojure.zip`.

Unfortunately `tools.analyzer.js` hasn't been updated to account for recent cljs changes so when we can't build an AST we're somewhat limited in what we can do.  Once that's fixed I'd guess most of our refactorings will work for both dialects.

I don't write any cljs lately so if there are any cljs specific refactorings that are missing I might not think of them myself.  Suggestions welcome!

**Comment by bilus** [comment]
Awesome! Thanks for a detailed response. That's fantastic. Good cljs support is definitely something I'm looking for; I wasn't aware that `tools.analyzer.js` is lagging behind cljs but that's only expected considering the pace at which things evolve in both the core and the ecosystem. 

Thanks again.
