### ISSUE TITLE
add-project-dependency does not work with boot

### ISSUE THREAD

**Issue by mbuczko** [clojure-emacs/clj-refactor.el#238]
unfortunately this extremely useful function expects a project.clj. boot bases on build.boot where it holds all project dependencies (actually in the same way as leiningen does, so maybe it's not as hard to fix it).

would be great to have this function working, as boot gets more and more popularity nowadays :)

**Comment by expez** [comment]
None of the maintainers are boot users and due to the architecture of boot some stuff currently isn't working .e.g `rename-file-or-dir` and some other stuff is only working through luck when the faux classpath and the real classpath are identical (like find-usages and renaming). Until boot explicitly adds tooling support which grants access to the real files, instead of their faux classpath version, boot will always be unattractive to me.

Given all that, if you want to start adding some boot support I'll happily merge the pull requests :)

I suspect that this is real easy to fix, and a good way to get into emacs hacking!

**Comment by expez** [comment]
Do you know if alembic works with boot @mbuczko?  We might be able to update `build.boot` but unless alembic works with boot hotloading won't work.

**Comment by alexander-yakushev** [comment]
I would be perfectly fine if clj-refactor just spitted `[library "version"]` at the current point if it detected it is inside `*.boot` file.

Right now my workflow is:

1. Go to `build.boot` file.
2. Execute `cljr-add-dependency`, select the library, glimpse at its latest version, and then `C-g`.
3. Write down the dependency vector manually, into the correct place in boot file.
4. Execute `cljr-hotload-dependency` hovering over the newly typed in vector.

**Comment by expez** [comment]
@alexander-yakushev or @mbuczko: I'd love a verification that this actually works as intended.

**Comment by alexander-yakushev** [comment]
@expez It almost works. Please see #268.

**Comment by mbuczko** [comment]
@expez just checked it out - dependencies are added to build.boot perfectly.
thanks for all the effort to make it working :)

**Comment by alexander-yakushev** [comment]
Indeed, thank you Lars!

**Comment by expez** [comment]
I just added boot support to `cljr-clean-ns`, `cljr-update-project-dependency`, `cljr-update-project-dependencies` and `cljr-sort-project-dependencies`.

**Comment by alexander-yakushev** [comment]
:+1:

**Comment by mbuczko** [comment]
awesome! now I feel almost like @magnars doing his magic in "parens of the dead" :)
