### ISSUE TITLE
`ef` doesn't work on a toplevel form

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#239]
`ef` on 

```clj
|(+ 1 1)
```

Does the wrong thing, but 

```clj
(do 
  |(+ 1 1))
```

works fine.

**Comment by benedekfazekas** [comment]
why is this a bug tho? is `ef` expected to work on a toplevel form?!

**Comment by expez** [comment]
> why is this a bug tho? 

Not sure it is, but I kind of expected this to work when I tried to do some QA on 1.2.0 earlier today.

> ef expected to work on a toplevel form?!

While not the intended usage, there's no reason for this not to work.  The only reason it fails now is because point isn't moved correctly after creating the new toplevel form.

**Comment by expez** [comment]
Hah, this wasn't as easy to fix as I had thought, and since it's a weird edge-case I'm inclined to just change my mind and not consider this a bug after all :p

**Comment by magnars** [comment]
I've stumbled on this one aswell. The reason I did, was I realized I had started implementing something that would be better in a separate function. Instead of renaming the current one and tamper with the params, I wanted to move the current code out.

If it is a difficult fix, how about this doozy: wrap it in `(do )` in the client first, then remove it after. ;-)

**Comment by expez** [comment]
Your use case should work fine, this only fails if you you try to run `ef` on a toplevel form, like the one in the OP.

**Comment by magnars** [comment]
Ok, it might have been fixed since I tried then. :)
