### ISSUE TITLE
Let me put together a 1.1.1 release that just fixes compatibility w/ CIDER 0.10.x?

### ISSUE THREAD

**Issue by cap10morgan** [clojure-emacs/clj-refactor.el#277]
I've got a local branch that cherry-picks just the commits to fix the compatibility issues between clj-refactor 1.1.0 and CIDER 0.10.x.

If you create a branch for it to target, I'd be happy to do a PR and keep a 1.1.x version alive and compatible with CIDER 0.10.x (and/or keep newer major and minor releases compatible if they don't depend on CIDER 0.11+ functionality).

(I'm assuming these compatibility issues are known because they seem to be fixed on master, but let me know if you'd like me to go into greater detail there.)

**Comment by benedekfazekas** [comment]
:+1: here

**Comment by expez** [comment]
The only reason do this would be to get a stable release out which doesn't need clj 1.7.  Is that your use-case @cap10morgan?

Otherwise we're basically ready to get 2.0.0 out the door. I just need to put a day aside to hack on cljr.

The only thing that can't be finished up within the scope of a day is potentially the new tracker, which replaces tools.namespace's tracker to handle namespaces with the same name across dialects.  @benedekfazekas made a strong case that this should be part of 2.0.0 and couldn't wait for 2.1.0 sometime later in January.

**Comment by cap10morgan** [comment]
@expez No, I don't need pre-1.7 clj support. I just want a stable release that works with the latest stable CIDER release. I'll hold tight for the 2.0 release.
