### ISSUE TITLE
Drop the s.el dependency

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/clj-refactor.el#293]
I see you're depending on Emacs 24.4. I'd suggest dropping s.el and simply using `subr-x.el` introduced there. The fewer deps, the better.

**Comment by expez** [comment]
Pull request welcome :)

**Comment by expez** [comment]
Awesome, @dotemacs :+1:

**Comment by benedekfazekas** [comment]
looks cool!

will try to find time to review in detail but so far looks really good. also not planning to merge this before releasing `2.3.0`

**Comment by benedekfazekas** [comment]
what is the problem with using `thread-last` here? https://github.com/clojure-emacs/clj-refactor.el/compare/master...dotemacs:no-more-s#diff-ad8315941dfda54547f9762bd5a52d04L305

**Comment by dotemacs** [comment]
Hey @benedekfazekas 

I knew that this question would come up :)

So I put the comment about it in the commit, pasting it here so that you don't have to go looking for it

> All the `thread-last` got unwound due to the re-write as s.el's `s-join`
expected separator first then the strings. Whereas subr-x.el's
`string-join` expects strings and then the separator.

https://github.com/dotemacs/clj-refactor.el/commit/da35e4ba51e0bda6139f47aec1290eab786f8d5d

So it was a case of should I keep `thread-last` just to keep it? Or should I write a function that uses `string-join` internally but takes arguments as `s-join` and reorders them for `string-join`?
I figured that just unwinding `thread-last` was the easiest option.
But if you have a prefered way of doing this, then please do share :)


Also, there are 2-3 functions more from s.el that I still need to re-write, that's why I haven't created the pull request just yet. I only put a comment here that I'm working on it, so that somebody else doesn't pick it up... 

Should I create a pull request now, if we're to have more discussion about the code?

As for when you'll merge this, no rush on my side.

**Comment by benedekfazekas** [comment]
ha, makes sense. sorry missed the commit comment.

PR: yes please. would be easier to comment stuff, etc.
