### ISSUE TITLE
Some way to sort keys :)

### ISSUE THREAD

**Issue by CampingScorpion** [clojure-emacs/clj-refactor.el#32]
I love sorting things :)

I'd love a function to sort maps for easier reading.

Also, sorted maps diff better in git when you make test changes. (You may only change things slightly but the way the map prints garbles the whole commit by rearranging the map totally, making it look like more things have changed than eally have changed.)

**Comment by ernestas** [comment]
Did you find a way to sort?

**Comment by Malabarba** [comment]
Honestly, I think this could go in clojure-mode. Now that it has vertical alignment of values, might be nice to sort keys too. @bbatsov WDYT?

**Comment by expez** [comment]
Sorting and pretty-printing would be a lot easier to do in the middleware.

**Comment by Malabarba** [comment]
I think sorting is simpler in the client. There's nothing complex about sorting key-val pairs alphabetically, so there's no need to add a layer of complexity by involving the server. 

Besides, by working directly with the text (instead of sending it back and forth as data) there is less stuff you need to worry about (like accidentally losing/adding metadata, or deleting comments).

**Comment by mahinshaw** [comment]
As a note.  I have just found the built in `sort-lines` to be useful here.  The only thing I find painful is the delimiters (braces) will get sorted to, so the map pairs need to be on their own lines
