### ISSUE TITLE
Can we make use of how-to-ns?

### ISSUE THREAD

**Issue by jcf** [clojure-emacs/clj-refactor.el#378]
I've been using [how-to-ns](https://github.com/gfredericks/how-to-ns) recently, and love how effective it is. Although it won't remove statements that aren't used like clj-refactor will, it does an excellent job of formatting your `ns` forms.

It seems between clj-refactor, cljfmt, and how-to-ns we have some overlap, and I was wondering if there's an effort to share the great work everyone's done so far.

Maybe we can vendor how-to-ns in the same way Cider vendors some Clojure dependencies and format namespaces using the code in how-to-ns?

**Comment by benedekfazekas** [comment]
thanks for raising this. to answer your first question i don't think there is any effort to share between these implementations. in fact i have not even heard about `how-to-ns` tbh -- my bad.

our  `clean-ns` is a very opinionated implementation too although you also have some options to configure its behaviour. can you please elaborate what you mean by your last question?

**Comment by expez** [comment]
> It seems between clj-refactor, cljfmt, and how-to-ns we have some overlap, and I was wondering if there's an effort to share the great work everyone's done so far.

I've asked about better pretty-printing support in cljfmt, to replace our own pretty-printing, but nobody wants to actually write that code.

We have some pretty-printing code that I hate and I would love to be able to replace that with something that works better (and is maintained by someone else!).

As it stands now, we can't really use it as part of `clean-ns` because it doesn't support all the clj dialects.

I'm open to revisiting this once that situation changes, though!
