### ISSUE TITLE
cljr-populate-artifact-cache-on-startup change default - or no?

### ISSUE THREAD

**Issue by paulrd** [clojure-emacs/clj-refactor.el#447]
https://github.com/clojure-emacs/refactor-nrepl/pull/264 requires cljr-populate-artifact-cache-on-startup to be set to nil. We might want to change the default to nil. This would make adding project dependencies to be slightly slower but once the PR in refactor-nrepl is active, this will be faster anyway for 2 reasons: 1. The clojars deps will be 1/8 th the former size (500KB) and 2. artifacts will be cached in a temporary file that will be used between start-ups unless it is longer than a day old.

**Comment by expez** [comment]
The intention was to have the cache be populated in anticipation of the first call to `cljr-add-project-dependency`.  I still think it's nice to not have to wait Unless the size reduction makes this nearly instantaneous?  If it isn't instant, I think we have two options:

1. Add another middleware paramenter, in addition to `force`, that would init if the cache is stale or nil.
2. Have the middleware unconditionally hit the network and populate the cache if it's stale or nil.

I think 1) is better, but it's a little bit more work.  What do you think?

**Comment by paulrd** [comment]
Yeah, I was just thinking (I haven't looked into the code much yet)... Isn't this parameter complecting 2 things? Why does having the list of artifacts available earlier require refreshing the cache even if it's not stale? It seems that :force is asking for the cache to be refreshed even if not stale, but it's also being used to somehow get the cache to populate early (I don't understand how that is done yet).

I think my PR in refactor-nrepl already does 2).

**Comment by expez** [comment]
> I think my PR in refactor-nrepl already does 2).

No, the `defonce` with the cache will be initialized to `{}` (if read from disk fails) unless `clj-refactor.el` tells the middleware to do something.

I think what's needed is:

1. `cljr--init-artifact-cache` which is essentially the same as `cljr--update-artifact-cache` without the `force` flag.  This should cause the middleware to init the cache, from disk or over the network if it's stale.
2. Use `cljr--init-artifact-cache` instead of `cljr--update-artifact-cache` in the conditional switch on `cljr--populate-artifact-cache-on-startup`

That should leave us with the desired behavior and a default value for this variable that is OK as it is.  What do you think?

**Comment by paulrd** [comment]
Ah right! Haha, already forgetting what my code does! That sounds like the right solution. Who wants to do the PRs? I don't mind doing either, none or both.

**Comment by expez** [comment]
> Who wants to do the PRs? I don't mind doing either, none or both.

Go ahead.  Appreciate the help! :)

**Comment by alexander-yakushev** [comment]
+1. Having this on by default causes terrible slowdowns in Emacs, it seems like Emacs keeps this data in memory, so its GC times become wildly higher.
